### ISSUE TITLE
[Comment] Really?

### ISSUE THREAD

**Issue by prtksxna** [samwilson/website#2]
Commenting about: https://samwilson.id.au/2020/0328_organising.html

[Please say whatever you want here. You can delete this line.]

**Comment by samwilson** [comment]
Yes, thank you very much. You are correct.

**Comment by prtksxna** [comment]
😅

**Comment by samwilson** [comment]
This is more comments than I've had in years.

**Comment by prtksxna** [comment]
You better add it to https://samwilson.id.au/2020/0328_organising.html
